controllers/DocumentosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Constants;
use app\models\Utils;
use app\models\logic\Empresa;
use app\models\logic\Usuario;
use app\models\logic\Categoria;
use app\models\logic\Documento;
use app\models\logic\Documento2;
use app\models\logic\Pago;
use app\models\search\UsuariosSearch;
use app\models\search\CategoriasSearch;
use app\models\search\DocumentosSearch;
use app\models\search\PagosSearch;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

/**
 * Description of DocumentosController
 *
 * @author Avuunita
 */
class DocumentosController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'menu', 'view'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create-folder', 'delete-folder', 'create-template', 'delete-template'],
                        'roles' => [Constants::NUM_SUPERVISOR, Constants::NUM_DIRECTOR, Constants::NUM_COORDINADOR],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create-file', 'delete-file', 'download'],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete-folder' => ['POST'],
                    'delete-template' => ['POST'],
                    'delete-file' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Usuario models.
     * @return mixed
     */
    public function actionIndex($id) {
        self::comprobarAcceso($id);

        $usuario = Usuario::findOne($id);
        $rol = $usuario->authAssignments[0]->item_name;
        $empresa = $usuario->empresa;

        $usuariosSearch = new UsuariosSearch();
        $categoriasSearch = new CategoriasSearch();

        $params = Yii::$app->request->queryParams;
        $categoriasDataProvider = $categoriasSearch->searchMenu($params);

        if ($rol == Constants::ROL_DIRECTOR) {
            $usuariosDataProvider = $usuariosSearch->buscarUsuarios($empresa, $params);
        } else if ($rol == Constants::ROL_COORDINADOR) {
            $usuariosDataProvider = $usuariosSearch->buscarProyectosCoordinador($usuario, $params);
        } else {
            $usuariosDataProvider = null;
        }

        return $this->render('index', [
                    'usuario' => $usuario,
                    'categoriasSearch' => $categoriasSearch,
                    'categoriasDataProvider' => $categoriasDataProvider,
                    'usuariosSearch' => $usuariosSearch,
                    'usuariosDataProvider' => $usuariosDataProvider,
        ]);
    }

    public function actionMenu($id, $c) {
        self::comprobarAcceso($id);

        $usuario = Usuario::findOne($id);
        $categoriaPadre = Categoria::findOne($c);

        $categoriasSearch = new CategoriasSearch();

        $params = Yii::$app->request->queryParams;
        $categoriasDataProvider = $categoriasSearch->searchSubmenu($c, $params);

        return $this->render('menu', [
                    'usuario' => $usuario,
                    'categoriaPadre' => $categoriaPadre,
                    'categoriasSearch' => $categoriasSearch,
                    'categoriasDataProvider' => $categoriasDataProvider,
        ]);
    }

    public function actionView($id, $c, $fp = null) {
        self::comprobarAcceso($id, $fp);

        $usuario = Usuario::findOne($id);
        $rol = $usuario->authAssignments[0]->item_name;
        $categoria = Categoria::findOne($c);

        $documentoPadre = null;
        if (isset($fp)) {
            $documentoPadre = Documento::findOne($fp);
        }

        $documentosSearch = new DocumentosSearch();
        $params = Yii::$app->request->queryParams;

        $datosCarpetas = $documentosSearch->buscarCarpetas($usuario, $categoria, $params, $documentoPadre);
        $datosPlantillas = $documentosSearch->buscarPlantillas($usuario, $categoria, $params, $documentoPadre);
        $datosArchivos = $documentosSearch->buscarArchivos($usuario, $categoria, $params, $documentoPadre);

        return $this->render('view', [
                    'usuario' => $usuario,
                    'categoria' => $categoria,
                    'documentoPadre' => $documentoPadre,
                    'documentosSearch' => $documentosSearch,
                    'datosCarpetas' => $datosCarpetas,
                    'datosPlantillas' => $datosPlantillas,
                    'datosArchivos' => $datosArchivos,
        ]);
    }

    public function actionCreateFolder($c, $fp = null) {
        $id = Yii::$app->user->id;
        self::comprobarAccesoFicheros($id, $fp);

        $roles = [Constants::NUM_SUPERVISOR, Constants::NUM_DIRECTOR, Constants::NUM_COORDINADOR];
        self::comprobarPermisos($roles, $c, Constants::ACCION_CREAR_CARPETA);

        $model = new Documento();
        $model->esPlantilla = Constants::varNoBD;
        $model->esFichero = Constants::varSiBD;

        $usuario = Usuario::findOne($id);
        $categoria = Categoria::findOne($c);

        $documentoPadre = null;
        if (isset($fp)) {
            $documentoPadre = Documento::findOne($fp);
        }

        $this->crearCarpeta($model, $usuario, $categoria, $documentoPadre);

        return $this->render('create-folder', [
                    'model' => $model,
                    'usuario' => $usuario,
                    'categoria' => $categoria,
                    'documentoPadre' => $documentoPadre,
        ]);
    }

    public function actionCreateFile($c, $fp = null) {
        $id = Yii::$app->user->id;
        self::comprobarAccesoFicheros($id, $fp);

        $roles = [Constants::NUM_SUPERVISOR, Constants::NUM_DIRECTOR, Constants::NUM_COORDINADOR, Constants::NUM_PROYECTO];
        self::comprobarPermisos($roles, $c, Constants::ACCION_SUBIR_ARCHIVO);

        $model = new Documento2();
        $model->esPlantilla = Constants::varNoBD;
        $model->esFichero = Constants::varNoBD;

        $usuario = Usuario::findOne($id);
        $categoria = Categoria::findOne($c);

        $documentoPadre = null;
        if (isset($fp)) {
            $documentoPadre = Documento::findOne($fp);
        }

        $this->subirArchivo($model, $usuario, $categoria, $documentoPadre);

        return $this->render('create-file', [
                    'model' => $model,
                    'usuario' => $usuario,
                    'categoria' => $categoria,
                    'documentoPadre' => $documentoPadre,
        ]);
    }

    public function actionCreateTemplate($c, $fp = null) {
        $id = Yii::$app->user->id;
        self::comprobarAccesoFicheros($id, $fp);

        $roles = [Constants::NUM_SUPERVISOR, Constants::NUM_DIRECTOR, Constants::NUM_COORDINADOR];
        self::comprobarPermisos($roles, $c, Constants::ACCION_SUBIR_ARCHIVO);

        $model = new Documento2();
        $model->esPlantilla = Constants::varSiBD;
        $model->esFichero = Constants::varNoBD;

        $usuario = Usuario::findOne($id);
        $categoria = Categoria::findOne($c);

        $documentoPadre = null;
        if (isset($fp)) {
            $documentoPadre = Documento::findOne($fp);
        }

        $this->subirArchivo($model, $usuario, $categoria, $documentoPadre, true);

        return $this->render('create-template', [
                    'model' => $model,
                    'usuario' => $usuario,
                    'categoria' => $categoria,
                    'documentoPadre' => $documentoPadre,
        ]);
    }

    /**
     * Permite crear una carpeta en el servidor.
     * @param Documento $model
     * @param Usuario $usuario
     * @param Categoria $categoria
     * @param Documento $documentoPadre
     * @return type
     */
    private function crearCarpeta($model, $usuario, $categoria, $documentoPadre) {
        if ($model->load(Yii::$app->request->post())) {
            $folder = $model->rutaArchivo;
            $model->rutaArchivo = Utils::encrypt($model->rutaArchivo);

            $idFicheroPadre = null;
            if (isset($documentoPadre)) {
                $idFicheroPadre = $documentoPadre->idDocumento;
            }

            $model->idUsuario = $usuario->id;
            $model->idCategoria = $categoria->idCategoria;
            $model->idFicheroPadre = $idFicheroPadre;

            $model->idUsuarioRegistro = $usuario->id;
            $model->idUsuarioActualizo = $usuario->id;
            $model->accionUsuario = Constants::accionUsuarioInsertar;
            $model->fechaRegistro = date('Y-m-d H:i:s');
            $model->fechaModificacion = date('Y-m-d H:i:s');

            $carpetas = Utils::obtenerRutaFicheros($documentoPadre);

            $path = Yii::$app->basePath . '/web/Archivos/';
            $path .= "$categoria->idCategoria/";
            for ($i = sizeof($carpetas) - 1; $i >= 0; $i--) {
                $docum = $carpetas[$i];
                $carpeta = Utils::decrypt($docum->rutaArchivo);
                $path .= "$docum->idUsuario-$carpeta/";
            }
            $path .= "$usuario->id-$folder/";

            $connection = \Yii::$app->db;
            $transaction = $connection->beginTransaction();
            $saved = false;

            if ($model->save(false)) {
                try {
                    $saved = FileHelper::createDirectory($path, $mode = 0775, $recursive = true);

views/documentos/_form-file.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use app\models\Utils;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\logic\Documento */
/* @var $usuario app\models\logic\Usuario */
/* @var $categoria app\models\logic\Categoria */
/* @var $documentoPadre app\models\logic\Documento */

$this->params['breadcrumbs'][] = ['label' => 'Documentos', 'url' => ['documentos/', 'id' => Yii::$app->user->id]];
$categoriaPadre = $categoria->categoriaPadre;
if ($usuario->id != Yii::$app->user->id) {
    $idL = Yii::$app->user->id;
    $usuarioL = Usuario::findOne($idL);
    $rolL = $usuarioL->authAssignments[0]->item_name;
    $rolI = $usuario->authAssignments[0]->item_name;
    $this->params['breadcrumbs'][] = ['label' => $usuario->name, 'url' => ['documentos/', 'id' => $usuario->id]];
}
$rutas = Utils::obtenerRutaCategorias($categoria);
for ($i = sizeof($rutas) - 1; $i > 0; $i--) {
    $this->params['breadcrumbs'][] = $rutas[$i]->nombre;
}
$this->params['breadcrumbs'][] = ['label' => $categoria->nombre, 'url' => ['documentos/view/', 'id' => $usuario->id, 'c' => $categoria->idCategoria, 'fp' => null]]; //
{
    $carpetas = Utils::obtenerRutaFicheros($documentoPadre);
    for ($i = sizeof($carpetas) - 1; $i >= 0; $i--) {
        $docum = $carpetas[$i];
        $carpeta = Utils::decrypt($docum->rutaArchivo);
        $this->params['breadcrumbs'][] = ['label' => $carpeta, 'url' => ['documentos/view', 'id' => $usuario->id, 'c' => $categoria->idCategoria, 'fp' => $docum->idDocumento]];
    }
}
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="documento-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    $tiempo = Utils::mostrarTiempoRestante();
    if (isset($tiempo)) {
        Yii::$app->session->setFlash($tiempo['type'], $tiempo['message']);
    }
    ?>

    <div class="documento-form">

        <?php
        $form = ActiveForm::begin([
                    'options' => ['enctype' => 'multipart/form-data']]);
        ?>

        <?=
        $form->field($model, 'archivo')->widget(FileInput::classname(), [
            'pluginOptions' => [
                'allowedFileExtensions' => ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'],
                'showUpload' => false,
            ],
        ]);
        ?>

        <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
        </div>

<?php ActiveForm::end(); ?>

    </div>

</div>

views/documentos/_form-folder.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Utils;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\logic\Documento */
/* @var $usuario app\models\logic\Usuario */
/* @var $categoria app\models\logic\Categoria */
/* @var $documentoPadre app\models\logic\Documento */

$this->title = 'Crear Carpeta';
$this->params['breadcrumbs'][] = ['label' => 'Documentos', 'url' => ['documentos/', 'id' => Yii::$app->user->id]];
$categoriaPadre = $categoria->categoriaPadre;
if ($usuario->id != Yii::$app->user->id) {
    $idL = Yii::$app->user->id;
    $usuarioL = Usuario::findOne($idL);
    $rolL = $usuarioL->authAssignments[0]->item_name;
    $rolI = $usuario->authAssignments[0]->item_name;
    $this->params['breadcrumbs'][] = ['label' => $usuario->name, 'url' => ['documentos/', 'id' => $usuario->id]];
}
$rutas = Utils::obtenerRutaCategorias($categoria);
for ($i = sizeof($rutas) - 1; $i > 0; $i--) {
    $this->params['breadcrumbs'][] = $rutas[$i]->nombre;
}
$this->params['breadcrumbs'][] = ['label' => $categoria->nombre, 'url' => ['documentos/view/', 'id' => $usuario->id, 'c' => $categoria->idCategoria, 'fp' => null]]; //
{
    $carpetas = Utils::obtenerRutaFicheros($documentoPadre);
    for ($i = sizeof($carpetas) - 1; $i >= 0; $i--) {
        $docum = $carpetas[$i];
        $carpeta = Utils::decrypt($docum->rutaArchivo);
        $this->params['breadcrumbs'][] = ['label' => $carpeta, 'url' => ['documentos/view', 'id' => $usuario->id, 'c' => $categoria->idCategoria, 'fp' => $docum->idDocumento]];
    }
}
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="documento-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    $tiempo = Utils::mostrarTiempoRestante();
    if (isset($tiempo)) {
        Yii::$app->session->setFlash($tiempo['type'], $tiempo['message']);
    }
    ?>

    <div class="documento-form">

        <?php
        $form = ActiveForm::begin();
        ?>

            <?= $form->field($model, 'rutaArchivo')->textInput(['maxlength' => true]) ?>

        <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
        </div>

<?php ActiveForm::end(); ?>

    </div>

</div>

views/documentos/create-file.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\logic\Documento */
/* @var $usuario app\models\logic\Usuario */
/* @var $categoria app\models\logic\Categoria */
/* @var $documentoPadre app\models\logic\Documento */

$this->title = 'Subir Archivo';
?>
<?=

$this->render('_form-file', [
    'model' => $model,
    'usuario' => $usuario,
    'categoria' => $categoria,
    'documentoPadre' => $documentoPadre,
])
?>

views/documentos/create-folder.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\logic\Documento */
/* @var $usuario app\models\logic\Usuario */
/* @var $categoria app\models\logic\Categoria */
/* @var $documentoPadre app\models\logic\Documento */
?>
<?=

$this->render('_form-folder', [
    'model' => $model,
    'usuario' => $usuario,
    'categoria' => $categoria,
    'documentoPadre' => $documentoPadre,
])
?>

views/documentos/create-template.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\logic\Documento */
/* @var $usuario app\models\logic\Usuario */
/* @var $categoria app\models\logic\Categoria */
/* @var $documentoPadre app\models\logic\Documento */

$this->title = 'Subir Plantilla';
?>
<?=

$this->render('_form-file', [
    'model' => $model,
    'usuario' => $usuario,
    'categoria' => $categoria,
    'documentoPadre' => $documentoPadre,
])
?>

views/documentos/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Constants;
use app\models\Utils;
use app\models\search\CategoriasSearch;

/* @var $this yii\web\View */
/* @var $usuario app\models\logic\Usuario */
/* @var $categoriasSearch app\models\search\CategoriasSearch */
/* @var $categoriasDataProvider yii\data\ActiveDataProvider */
/* @var $usuariosSearch app\models\search\UsuariosSearch */
/* @var $usuariosDataProvider yii\data\ActiveDataProvider */

$this->title = 'Documentos';
if ($usuario->id != Yii::$app->user->id) {
    $this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['documentos/', 'id' => Yii::$app->user->id]];
    $this->params['breadcrumbs'][] = $usuario->name;
} else {
    $this->params['breadcrumbs'][] = $this->title;
}
?>
<div class="documento-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
//    $this->registerJsFile(
//            '@web/js/loadTime.js', ['depends' => [\yii\web\JqueryAsset::className()]]
//    );
    $tiempo = Utils::mostrarTiempoRestante();
    if (isset($tiempo)) {
        Yii::$app->session->setFlash($tiempo['type'], $tiempo['message']);
    }
    ?>
    <!--div id="tiempo"></div-->

    <?=
    GridView::widget([
        'dataProvider' => $categoriasDataProvider,
        'columns' => [
            [
                'header' => $usuario->id,
                'headerOptions' => ['hidden' => true,],
                'format' => 'raw',
                'value' => function ($model, $key, $index, $column) {
            /* @var $column yii\grid\DataColumn */
            if ($model->tipo == Constants::tipoAuxiliar) {
                $idCategoria = $model->idCategoria;
                $idUsuario = $column->header;
                $params = Yii::$app->request->queryParams;
                $categoriasSearch = new CategoriasSearch();
                $dataProvider = $categoriasSearch->searchSubmenu($idCategoria, $params);
                if (sizeof($dataProvider->models) > 0) {
                    $url = Html::a($model->nombre, ['documentos/menu', 'id' => $idUsuario, 'c' => $idCategoria]);
                } else {
                    $url = Html::a($model->nombre, ['documentos/view', 'id' => $idUsuario, 'c' => $idCategoria, 'fp' => null]);
                }
            } else {
                $url = $model->nombre;
            }

            switch ($model->nivel) {
                case 1:
                    $url = "<b>$url</b>";
                    break;
                case 2:
                    if ($model->tipo == Constants::tipoMayor) {
                        $url = "<ul><i>$url</i></ul>";
                    } else {
                        $url = "<ul>$url</ul>";
                    }
                    break;
                default:
                    $url = "<ul><ul>$url</ul></ul>";
                    break;
            }
            return $url;
        },
            ],
        ],
    ]);
    ?>

    <?php
    if (!is_null($usuariosDataProvider)) {
        ?>
        <h1><?= Html::encode("Proyectos") ?></h1>

        <?=
        GridView::widget([
            'dataProvider' => $usuariosDataProvider,
            'columns' => [
                [
                    'headerOptions' => ['hidden' => true,],
                    'format' => 'raw',
                    'value' => function ($model) {
                $url = Html::a($model->name, ['documentos/', 'id' => $model->id]);
                return $url;
            },
                ], [
                    'headerOptions' => ['hidden' => true,],
                    'attribute' => 'Rol',
                    'format' => 'raw',
                    'value' => function ($model) {
                return Utils::getRol($model->authAssignments[0]->item_name);
            },
                ],
            ],
        ]);
    }
    ?>
</div>

views/documentos/menu.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\logic\Usuario;
use app\models\Constants;
use app\models\Utils;

/* @var $this yii\web\View */
/* @var $usuario app\models\logic\Usuario */
/* @var $categoriaPadre app\models\logic\Categoria */
/* @var $categoriasSearch app\models\search\CategoriasSearch */
/* @var $categoriasDataProvider yii\data\ActiveDataProvider */

$this->title = 'Documentos';
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['documentos/', 'id' => Yii::$app->user->id]];
if ($usuario->id != Yii::$app->user->id) {
    $idL = Yii::$app->user->id;
    $usuarioL = Usuario::findOne($idL);
    $rolL = $usuarioL->authAssignments[0]->item_name;
    $rolI = $usuario->authAssignments[0]->item_name;
    $this->params['breadcrumbs'][] = ['label' => $usuario->name, 'url' => ['documentos/', 'id' => $usuario->id]];
}
$rutas = Utils::obtenerRutaCategorias($categoriaPadre);
for ($i = sizeof($rutas) - 1; $i > 1; $i--) {
    $this->params['breadcrumbs'][] = $rutas[$i]->nombre;
}
$this->params['breadcrumbs'][] = ['label' => $rutas[1]->nombre, 'url' => ['documentos/', 'id' => $usuario->id]];
$this->params['breadcrumbs'][] = ['label' => $categoriaPadre->nombre, 'url' => ['documentos/menu', 'id' => $usuario->id, 'c' => $categoriaPadre->idCategoria, 'fp' => null]];
?>
<div class="documento-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    $tiempo = Utils::mostrarTiempoRestante();
    if (isset($tiempo)) {
        Yii::$app->session->setFlash($tiempo['type'], $tiempo['message']);
    }
    ?>

    <?=
    GridView::widget([
        'dataProvider' => $categoriasDataProvider,
        'columns' => [
            [
                'attribute' => $usuario->id,
                'header' => 'Archivo',
                'format' => 'raw',
                'value' => function ($model, $key, $index, $column) {
                    /* @var $column yii\grid\DataColumn */
                    $idCategoria = $model->idCategoria;
                    $idUsuario = $column->attribute;
                    if ($model->tipo == Constants::tipoAuxiliar || $model->tipo == Constants::tipoCombinado) {
                        $url = Html::a($model->nombre, ['documentos/view', 'id' => $idUsuario, 'c' => $idCategoria, 'fp' => null]);
                    } else {
                        $url = $model->nombre;
                    }

                    switch ($model->nivel) {
                        case 1:
                            $url = "<b>$url</b>";
                            break;
                        default:
                            $url = "$url";
                            break;
                    }
                    return $url;
                },
                    ],
                    'formato',
                    'fechaDiligenciamiento',
                ],
            ]);
            ?>
</div>